import axios from "axios";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useState } from "react";
import { toast } from "react-toastify";

export default function register() {
  const [inputName, setInputName] = useState("");
  const [inputEmail, setInputEmail] = useState("");
  const [inputPass, setInputPass] = useState("");
  const router = useRouter();

  const handleLogin = async (e) => {
    e.preventDefault();
    //code for registration user
    var data = JSON.stringify({
      email: inputEmail,
      name: inputName,
      password: inputPass,
    });

    var config = {
      method: "post",
      url: "https://staging-be-ecom.techserve4u.com/api/user/signup",
      headers: {
        "Content-Type": "application/json",
      },
      data: data,
    };

    await axios(config)
      .then(function (response) {
        console.log(JSON.stringify(response.data));
        toast.success("signup successful.");
        router.push("/");
      })
      .catch(function (error) {
        console.log(error);
      });

    // console.log(inputEmail);
    // console.log(inputName);
    // console.log(inputPass);
  };
  return (
    <div>
      <Head>
        <title>Sign up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className=" bg-gray-100 w-full h-screen flex align-middle justify-center">
          <div className="bg-white border w-80 m-auto p-4 rounded-lg">
            <h3>Create an Account</h3>
            <div className="flex min-h-full items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
              <div className="w-full max-w-md space-y-8">
                <form className="mt-2 space-y-6" onSubmit={handleLogin}>
                  <div className=" rounded-md shadow-sm">
                    <div className="my-3">
                      <label
                        htmlFor="username"
                        className="text-xs text-gray-400"
                      >
                        username
                      </label>
                      <input
                        onChange={(e) => setInputName(e.target.value)}
                        id="username"
                        name="username"
                        type="text"
                        required
                        className="relative block w-full appearance-none rounded-md border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm"
                        placeholder="username "
                      />
                    </div>
                    <div className="my-3">
                      <label htmlFor="email" className="text-gray-400 text-xs">
                        Email
                      </label>
                      <input
                        onChange={(e) => setInputEmail(e.target.value)}
                        id="email"
                        name="email"
                        type="email"
                        autoComplete="email"
                        required
                        className="relative block w-full appearance-none rounded-md border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm"
                        placeholder="Your email"
                      />
                    </div>

                    <div>
                      <label
                        htmlFor="password"
                        className="text-xs text-gray-400"
                      >
                        Create Password
                      </label>
                      <input
                        onChange={(e) => setInputPass(e.target.value)}
                        id="password"
                        name="password"
                        type="password"
                        autoComplete="current-password"
                        required
                        className="relative block w-full appearance-none rounded-md border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm"
                        placeholder="Password"
                      />
                    </div>
                  </div>

                  <div>
                    <button
                      type="submit"
                      className="group relative flex w-full justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
                    >
                      <span className="absolute inset-y-0 left-0 flex items-center pl-3"></span>
                      Sign Up
                    </button>
                  </div>
                </form>
                <p className="text-sm">
                  Already have account?{" "}
                  <Link
                    href="/"
                    className="font-bold text-indigo-600 hover:text-indigo-500"
                  >
                    Login
                  </Link>{" "}
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
